targets:
  $default:
    builders:
      loxia_generators:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/integration/*
            - test/integration/**/*

builders:
  loxia_generators:
    import: "package:loxia_generators/builder.dart"
    builder_factories: ["loxiaBuilder"]
    build_extensions: {".dart": [".loxia.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]